# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  inscription:
    from_email: "ne_pas_repondre@declarvins.fr"
    from_name:  "Webmaster DéclarVins"
    subject:    "DéclarVins - Votre contrat"
  etablissements:
    familles:
      "Producteur": ["Producteur cave particulière", "Producteur cave coopérative"]
      "Négociant": ["Négociant régional", "Négociant hors région"]
      "Vinificateur": ["Vinificateur"]
      "Courtier": ["Courtier"]