all:
  configuration:
    ds:
      name: "Enquête Stock"
      title: "Enquête Stock de Rosé millésime %millesime% ou précédent"
      product_hash_regex_filter: "/certifications\/AOP\/.+\/couleurs\/rose/"
      product_detail_interpro: "INTERPRO-CIVP"
      date_stock_declaration: '2025-07-31'
      hide_historique: true
      exception_produit: "certifications/AOP/genres/TRANQ/appellations/BAN/mentions/DEFAUT/lieux/DEFAUT/couleurs/rose"
