# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Declaration routing
homepage:
  url:   /contrat
  param: { module: contrat, action: index }

compte_nouveau:
  url:   /compte/nouveau/:nocontrat
  param: { module: acVinCompte, action: nouveau, nocontrat: null }
contrat_nouveau:
  url:   /contrat/nouveau/:nocontrat
  param: { module: contrat, action: nouveau, nocontrat: null }
contrat_etablissement_modification:
  url:   /contrat/etablissement/:indice/modification/:recapitulatif
  param: { module: contrat, action: modificationEtablissement, indice: null, recapitulatif: null }
contrat_etablissement_nouveau:
  url:   /contrat/etablissement/nouveau
  param: { module: contrat, action: nouveauEtablissement }
contrat_etablissement_suppression:
  url:   /contrat/etablissement/:indice/suppression/:recapitulatif
  param: { module: contrat, action: suppressionEtablissement, indice: null, recapitulatif: null  }
contrat_etablissement_recapitulatif:
  url:   /contrat/recapitulatif
  param: { module: contrat, action: recapitulatif }
contrat_etablissement_confirmation:
  url:   /contrat/confirmation
  param: { module: contrat, action: confirmation }
contrat_pdf:
  url:   /contrat/pdf
  param: { module: contrat, action: pdf }

# Validation routing
validation_login:
  url:   /validation/login
  param: { module: validation, action: login }
validation_fiche:
  url:   /validation/fiche
  param: { module: validation, action: fiche }
validation_compte:
  url:   /validation/compte
  param: { module: validation, action: compte }
validation_liaison:
  url:   /validation/liaison
  param: { module: validation, action: liaison }
validation_validation:
  url:   /validation/validation
  param: { module: validation, action: validation }
validation_archiver:
  url:   /validation/archiver/:etablissement
  param: { module: validation, action: archiver, etablissement: null }
validation_desarchiver:
  url:   /validation/desarchiver/:etablissement
  param: { module: validation, action: desarchiver, etablissement: null }
validation_delier:
  url:   /validation/delier/:etablissement
  param: { module: validation, action: delier, etablissement: null }
validation_lier:
  url:   /validation/lier/:etablissement
  param: { module: validation, action: lier, etablissement: null }

# Interpro routing
interpro_import:
  url:   /interpro/:id/update_etablissements
  param: { module: interpro, action: updateEtablissements, id: null }
interpro_upload_csv:
  url:   /interpro/:id/upload_csv
  param: { module: interpro, action: uploadCsv, id: null }

# Rush II : DRM routing
tiers:
  url: /tiers
  param: { module: tiers, action: login }
login:
  url: /login
  param: {module: acVinCompte, action: login}
logout:
  url: /logout
  param: {module: acVinCompte, action: logout}

# BO
admin:
  url: /admin
  param: { module: admin, action: index }
## Produit routing
produits:
  url: /admin/produits
  param: {module: produit, action: index}
produit_nouveau:
  url: /admin/produit/nouveau
  param: {module: produit, action: nouveau }
produit_modification:
  url: /admin/produit/:noeud/modification/:hash
  param: {module: produit, action: modification, hash: null, noeud: null}
produit_suppression:
  url: /admin/produit/:noeud/suppression/:hash
  param: {module: produit, action: suppression, hash: null, noeud: null}
## Etablissement routing
etablissement_login:
  url: /admin/etablissements
  param: {module: admin, action: etablissementLogin}
  
  
## Administration des Comptes
admin_comptes:
  url:   /admin/comptes
  param: { module: acVinCompteAdmin, action: index }
  
compte:
  url:   /admin/compte/:login
  param: { module: acVinCompteAdmin, action: compte }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
