# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Declaration routing
homepage:
  url:   /contrat
  param: { module: contrat, action: index }
contrat_valide:
  url:   /contrat/valide
  param: { module: contrat, action: valide }
compte_nouveau:
  url:   /compte/nouveau/:nocontrat
  param: { module: acVinCompte, action: nouveau, nocontrat: null }
compte_inexistant:
  url:   /compte/erreur/:login
  param: { module: acVinCompte, action: compteInexistant, login: null }
compte_partenaire:
  url:   /partenaire/erreur
  param: { module: acVinCompte, action: comptePartenaire }
acces_interdit:
  url:   /acces/erreur
  param: { module: acVinCompte, action: accesInterdit }
compte_valide:
  url:   /compte/valide
  param: { module: acVinCompte, action: valide }
compte_password:
  url:   /compte/mot-de-passe/:login
  param: { module: acVinCompte, action: redefinitionPassword, login: null }
compte_lost_password:
  url:   /compte/mot-de-passe-oublie
  param: { module: acVinCompte, action: lostPassword }
contrat_nouveau:
  url:   /contrat/nouveau/:nocontrat
  param: { module: contrat, action: nouveau, nocontrat: null }
contrat_etablissement_modification:
  url:   /contrat/etablissement/:indice/modification/:recapitulatif
  param: { module: contrat, action: modificationEtablissement, indice: null, recapitulatif: null }
contrat_etablissement_nouveau:
  url:   /contrat/etablissement/nouveau
  param: { module: contrat, action: nouveauEtablissement }
contrat_etablissement_suppression:
  url:   /contrat/etablissement/:indice/suppression/:recapitulatif
  param: { module: contrat, action: suppressionEtablissement, indice: null, recapitulatif: null  }
contrat_etablissement_recapitulatif:
  url:   /contrat/recapitulatif
  param: { module: contrat, action: recapitulatif }
contrat_etablissement_confirmation:
  url:   /contrat/confirmation/:send
  param: { module: contrat, action: confirmation, send: null }
contrat_pdf:
  url:   /contrat/pdf.:format
  param: { module: contrat, action: pdf, format: (html|pdf) }

# Validation routing
validation_login:
  url:   /validation/login
  param: { module: validation, action: login }
validation_suppression:
  url:   /validation/:num_contrat/suppression
  param: { module: validation, action: suppression }
validation_fiche:
  url:   /validation/fiche/:num_contrat
  param: { module: validation, action: fiche, num_contrat: null }
validation_pdf:
  url:   /validation/:num_contrat/pdf
  param: { module: validation, action: pdf, num_contrat: null }
validation_compte:
  url:   /validation/:num_contrat/compte
  param: { module: validation, action: compte, num_contrat: null }
validation_liaison:
  url:   /validation/:num_contrat/liaison
  param: { module: validation, action: liaison, num_contrat: null }
validation_validation:
  url:   /validation/:num_contrat/validation
  param: { module: validation, action: validation, num_contrat: null }
validation_delier:
  url:   /validation/:num_contrat/delier/:etablissement
  param: { module: validation, action: delier, etablissement: null, num_contrat: null }
validation_lier:
  url:   /validation/:num_contrat/lier/:etablissement
  param: { module: validation, action: lier, etablissement: null, num_contrat: null }
validation_compte_password:
  url:   /validation/compte-password/:login
  param: { module: validation, action: redefinitionPassword }

# Interpro routing
interpro_upload_csv:
  url:   /interpro/:id/upload_csv
  param: { module: interpro, action: uploadCsv, id: null }
interpro_upload_csv_volumes_bloques:
  url:   /interpro/upload_csv_volumes_bloques
  param: { module: interpro, action: uploadCsvVolumesBloques }

# Rush II : DRM routing
tiers_mon_espace:
  class: EtablissementRoute
  url: /etablissement/:identifiant
  param: { module: tiers, action: monEspace }
  requirements: { sf_method: ['get'] }
  options: { model: Etablissement, type: object }

tiers:
  url: /tiers
  param: { module: tiers, action: login }
tiers_forbidden:
  url: /tiers/acces-restreint
  param: { module: tiers, action: accessForbidden }
profil:
  class: EtablissementRoute
  url: /profil/:identifiant
  param: { module: tiers, action: profil }
  requirements: { sf_method: ['get', 'post'] }
  options: { model: Etablissement, type: object }
profil_statut:
  class: EtablissementRoute
  url: /profil/:identifiant/statut
  param: { module: tiers, action: statut }
  requirements: { sf_method: ['get', 'post'] }
  options: { model: Etablissement, type: object }
login:
  url: /login
  param: {module: acVinCompte, action: login}
logout:
  url: /logout
  param: {module: acVinCompte, action: logout}

# BO
admin:
  url: /admin
  param: { module: admin, action: index }
admin_libelles:
  url: /admin/libelles
  param: { module: admin, action: libelles }
admin_libelles_edit:
  url: /admin/libelles/:type/modification/:key
  param: { module: admin, action: libelleModification, key: null, type: null }
## Alerte routing
alertes:
  url: /admin/alertes
  param: {module: alerte, action: alertes}
alerte_edit:
  url: /admin/alertes/:id/modification/:campagne/:etablissement
  param: { module: alerte, action: alerteModification, id: null, campagne: null, etablissement: null }
## Produit routing
produits:
  url: /admin/produits
  param: {module: produit, action: index}
produit_nouveau:
  url: /admin/produit/nouveau
  param: {module: produit, action: nouveau }
produit_modification:
  url: /admin/produit/:noeud/modification/:hash
  param: {module: produit, action: modification, hash: null, noeud: null}
produit_suppression:
  url: /admin/produit/:noeud/suppression/:hash
  param: {module: produit, action: suppression, hash: null, noeud: null}
## Etablissement routing
etablissement_login:
  url: /admin/etablissements/drm
  param: {module: admin, action: etablissementDRMLogin}
etablissement_login_daids:
  url: /admin/etablissements/daids
  param: {module: admin, action: etablissementDAIDSLogin}
etablissement_profil_login:
  url: /admin/etablissements-profil
  param: {module: admin, action: etablissementProfilLogin}

## Administration des Comptes
admin_comptes:
  url:   /admin/comptes
  param: { module: acVinCompteAdmin, action: index }

compte_ajout:
  url:   /admin/compte-ajout
  param: { module: acVinCompteAdmin, action: compteAjout }

compte_recap:
  url:   /admin/compte-recap/:login
  param: { module: acVinCompteAdmin, action: compteRecap }
  
compte_suppression:
  url:   /admin/compte-supprimer/:login
  param: { module: acVinCompteAdmin, action: compteSuppression }
  
compte_creation:
  url:   /admin/compte-creer/:login
  param: { module: acVinCompteAdmin, action: compteCreation }

compte_modification:
  url:   /admin/compte-modification/:login
  param: { module: acVinCompteAdmin, action: compteModification }

compte_autocomplete:
  url: /admin/comptes-autocomplete
  param: {module: acVinCompteAdmin, action: compteAutocomplete}

admin_compte_password:
  url:   /admin/compte-password/:login
  param: { module: acVinCompteAdmin, action: redefinitionPassword }
  
partenaire_comptes:
  url:   /partenaire/comptes
  param: { module: ComptePartenaire, action: index }

compte_partenaire_ajout:
  url:   /partenaire/compte-ajout
  param: { module: ComptePartenaire, action: compteAjout }
  
compte_partenaire_suppression:
  url:   /partenaire/compte-supprimer/:login
  param: { module: ComptePartenaire, action: compteSuppression }
  
compte_partenaire_creation:
  url:   /partenaire/compte-creer/:login
  param: { module: ComptePartenaire, action: compteCreation }

compte_partenaire_modification:
  url:   /partenaire/compte-modification/:login
  param: { module: ComptePartenaire, action: compteModification }

partenaire_compte_password:
  url:   /partenaire/compte-password/:login
  param: { module: ComptePartenaire, action: redefinitionPassword }
  
oioc_comptes:
  url:   /oioc/comptes
  param: { module: CompteOIOC, action: index }

compte_oioc_ajout:
  url:   /oioc/compte-ajout
  param: { module: CompteOIOC, action: compteAjout }
  
compte_oioc_suppression:
  url:   /oioc/compte-supprimer/:login
  param: { module: CompteOIOC, action: compteSuppression }
  
compte_oioc_creation:
  url:   /oioc/compte-creer/:login
  param: { module: CompteOIOC, action: compteCreation }

compte_oioc_modification:
  url:   /oioc/compte-modification/:login
  param: { module: CompteOIOC, action: compteModification }

oioc_compte_password:
  url:   /oioc/compte-password/:login
  param: { module: CompteOIOC, action: redefinitionPassword }
  
# Statiques
statiques:
  url:   /statiques
  param: { module: statiques, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
