# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Declaration routing
homepage:
  url:   /
  param: { module: contrat, action: nouveau }

compte_nouveau:
  url:   /compte/nouveau
  param: { module: compte, action: nouveau }
contrat_nouveau:
  url:   /contrat/nouveau
  param: { module: contrat, action: nouveau }
contrat_etablissement_modification:
  url:   /contrat/etablissement/:indice/modification/:recapitulatif
  param: { module: contrat, action: modificationEtablissement, indice: null, recapitulatif: null }
contrat_etablissement_nouveau:
  url:   /contrat/etablissement/nouveau
  param: { module: contrat, action: nouveauEtablissement }
contrat_etablissement_suppression:
  url:   /contrat/etablissement/:indice/suppression/:recapitulatif
  param: { module: contrat, action: suppressionEtablissement, indice: null, recapitulatif: null  }
contrat_etablissement_recapitulatif:
  url:   /contrat/recapitulatif
  param: { module: contrat, action: recapitulatif }
contrat_etablissement_confirmation:
  url:   /contrat/confirmation
  param: { module: contrat, action: confirmation }
contrat_pdf:
  url:   /contrat/pdf
  param: { module: contrat, action: pdf }

# Validation routing
validation_login:
  url:   /validation/login
  param: { module: validation, action: login }
validation_fiche:
  url:   /validation/fiche
  param: { module: validation, action: fiche }
validation_compte:
  url:   /validation/compte
  param: { module: validation, action: compte }
validation_liaison:
  url:   /validation/liaison
  param: { module: validation, action: liaison }
validation_validation:
  url:   /validation/validation
  param: { module: validation, action: validation }
validation_import:
  url:   /validation/import
  param: { module: validation, action: import }
validation_archiver:
  url:   /validation/archiver/:etablissement
  param: { module: validation, action: archiver, etablissement: null }
validation_delier:
  url:   /validation/delier/:etablissement
  param: { module: validation, action: delier, etablissement: null }
validation_upload_csv:
  url:   /validation/upload_csv
  param: { module: validation, action: uploadCsv }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
