# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: contrat, action: index }
compte:
  url:   /compte
  param: { module: compte, action: index }
compte_new_chai:
  url:   /compte/chai/nouveau
  param: { module: compte, action: newChai }
compte_update_chai:
  url:   /compte/chai/:id/update
  param: { module: compte, action: updateChai, id: null }
compte_liaison_interpro:
  url:   /compte/liaison-interpro
  param: { module: compte, action: liaisonInterpro }
compte_validation:
  url:   /compte/validation
  param: { module: compte, action: validation }

compte_nouveau:
  url:   /compte/nouveau
  param: { module: compte, action: nouveau }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
