# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# A TESTER
upload_etablissements:
  url: /edi/etablissements/csv/:id
  param: {module: edi, action: uploadEtablissements}
# OK
streamDRMEdi:
  url: /edi/drm/:interpro/:datedebut
  param: {module: edi, action: streamDRM}
streamDRMEtablissementEdi:
  url: /edi/etablissement/drm/:etablissement/:datedebut
  param: {module: edi, action: streamDRMEtablissement, datedebut: null}
streamCampagneDRMEdi:
  url: /edi/campagne/drm/:interpro/:campagne
  param: {module: edi, action: streamCampagneDRM}
streamAnneeDRMEdi:
  url: /edi/annee/drm/:interpro/:annee
  param: {module: edi, action: streamAnneeDRM}
streamVracEdi:
  url: /edi/vrac/:interpro/:datedebut
  param: {module: edi, action: streamVrac}
streamVracEtablissementEdi:
  url: /edi/etablissement/vrac/:etablissement/:datedebut
  param: {module: edi, action: streamVracEtablissement, datedebut: null}
streamDAIDSEdi:
  url: /edi/daids/:interpro/:datedebut
  param: {module: edi, action: streamDAIDS}
streamStatistiquesBilanDrm:
  url: /edi/statistiques-bilan-drm/:interpro/:campagne
  param: {module: edi, action: streamStatistiquesBilanDrm}
pushDRMEtablissementEdi:
  url: /edi/push/etablissement/drm/:etablissement
  param: {module: edi, action: pushDRMEtablissement}
pushVracEtablissementEdi:
  url: /edi/push/etablissement/vrac/:etablissement
  param: {module: edi, action: pushVracEtablissement}
viewDRMEdi:
  url: /edi/drm/:identifiant/:annee/:mois/:rectificative
  param: {module: edi, action: viewDRM, rectificative: ''}
pushGrcEdi:
  url: /edi/push/grc/:interpro
  param: {module: edi, action: pushGrc}
streamGrcEdi:
  url: /edi/grc/:interpro
  param: {module: edi, action: streamGrc}
