# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# A TESTER
upload_etablissements:
  url: /edi/etablissements/csv/:id
  param: {module: edi, action: uploadEtablissements}
# OK
DRMPushEdi:
  url: /edi/v2/push/etablissement/drm/:etablissement
  param: {module: edi, action: pushDRMEtablissementV2}
GetBilanDRMEdi:
  url: /edi/v2/bilan/etablissement/drm/:etablissement
  param: {module: edi, action: getBilanDrmEtablissement}

testDRMEdi:
  url: /edi/v2/drm/:id_drm.:format
  param: {module: edi, action: ediV2, format: csv}
  requirements: {format: (csv|xml|debug)}
streamDAEEdi:
  url: /edi/dae/:interpro/:datedebut
  param: {module: edi, action: streamDAE}
streamDRMEdi:
  url: /edi/drm/:interpro/:datedebut
  param: {module: edi, action: streamDRM}
streamDRMInterpro:
  url: /edi/v2/drm/:interpro/:datedebut
  param: {module: edi, action: streamDRMInterpro}
streamVracInterpro:
  url: /edi/v2/contrats-achat/:interpro
  param: {module: edi, action: streamVracInterpro}
streamDRMEtablissementEdi:
  url: /edi/etablissement/drm/:etablissement/:datedebut
  param: {module: edi, action: streamDRMEtablissement, datedebut: null}
streamCampagneDRMEdi:
  url: /edi/campagne/drm/:interpro/:campagne
  param: {module: edi, action: streamCampagneDRM}
streamAnneeDRMEdi:
  url: /edi/annee/drm/:interpro/:annee
  param: {module: edi, action: streamAnneeDRM}
streamVracEdi:
  url: /edi/vrac/:interpro/:datedebut
  param: {module: edi, action: streamVrac}
streamTransactionEdi:
  url: /edi/transaction/:oioc/:datedebut
  param: {module: edi, action: streamTransaction, datedebut: null}
streamVracEtablissementEdi:
  url: /edi/etablissement/vrac/:etablissement/:datedebut
  param: {module: edi, action: streamVracEtablissement, datedebut: null}
streamDAIDSEdi:
  url: /edi/daids/:interpro/:datedebut
  param: {module: edi, action: streamDAIDS}
streamStatistiquesBilanDrm:
  url: /edi/statistiques-bilan-drm/:interpro/:campagne
  param: {module: edi, action: streamStatistiquesBilanDrm}
streamStatistiquesBilanDrmManquantes:
  url: /edi/statistiques-bilan-drm-manquantes/:interpro/:campagne/:periode
  param: {module: edi, action: streamStatistiquesBilanDrmManquantes}
pushTransactionEdi:
  url: /edi/push/transaction/:oioc
  param: {module: edi, action: pushTransaction}
pushDRMEtablissementEdi:
  url: /edi/push/etablissement/drm/:etablissement
  param: {module: edi, action: pushDRMEtablissement}
pushVracEtablissementEdi:
  url: /edi/push/etablissement/vrac/:etablissement
  param: {module: edi, action: pushVracEtablissement}
viewDRMEdi:
  url: /edi/drm/:identifiant/:annee/:mois/:rectificative
  param: {module: edi, action: viewDRM, rectificative: ''}
pushGrcEdi:
  url: /edi/push/grc/:interpro
  param: {module: edi, action: pushGrc}
streamGrcEdi:
  url: /edi/grc/:interpro
  param: {module: edi, action: streamGrc}
