<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/09/13 17:14:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=declarweb',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
