## YAML Template.

default:
  metas:
    title:        "Contrat"
    
soussigneSuccess:
  metas:
    title:        "Contrat - Soussigné"
    
marcheSuccess:
  metas:
    title:        "Contrat N° %d - Marché"

conditionSuccess:
  metas:
    title:        "Contrat N° %d - Condition"
    
validationSuccess:
  metas:
    title:        "Contrat N° %d - Validation"