<tr>
	<th><strong>Cat.</strong></th>
	<th><strong>Dénom.</strong></th>
	<th><strong>Lieu</strong></th>
	<th><strong>Couleur</strong></th>
	<th><strong>Cépage</strong></th>
	<th><strong>Millésime</strong></th>
	<th><strong>Dép.</strong></th>
	<th><strong>Labels</strong></th>  
	<th><strong>Douane</strong></th> 
	<th><strong>CVO</strong></th>    
	<th><strong>Repli</strong></th>   
	<th><strong>Déclassement</strong></th>
</tr>